---
title: "Model"
output: html_document
---

Key columns: 
* `hex_id`: integer
* `day`: Date
* `CODREG`: numeric

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T)

library(sf)
library(ggplot2)
library(dplyr)
library(tidyr)
library(zoo)
library(viridis)
library(gridExtra)
library(spdep)
library(parallel)
library(broom)
library(dotwhisker)
library(knitr)
library(readxl)
library(humidity)
```

```{r}
load("../grid/hex_ita_10km.sf.RData")
load("../air_quality/airquality.df.RData")
load("../air_quality/era5_climate_hex.df.RData")
load("../dead/hex_dead.df.RData")
load("../covid-cases-prov/reg_testing.df.RData")
load("../locked-down-comune/hex_pop_lockdown.RData")
load("../pop_density/pop_densities.df.RData")
```

```{r}
# Region misconding
hex_ita_10km.sf$CODREG[hex_ita_10km.sf$REGIONE == "Abruzzo"] <- '13'
hex_ita_10km.sf$CODREG[hex_ita_10km.sf$REGIONE == "Basilicata"] <- '17'
hex_ita_10km.sf$CODREG[hex_ita_10km.sf$REGIONE == "Emilia-Romagna"] <- '8'
hex_ita_10km.sf$CODREG[hex_ita_10km.sf$REGIONE == "Liguria"] <- '7'
```


# Variables

## Dependent variable

```{r}
m <- 
  expand.grid(hex_ita_10km.sf$hex_id, 
              paste0("T_", 15:20), 
              unique(hex_dead.df$day))
names(m) <- c("hex_id","year","day")

hex_dead.df <- merge(hex_dead.df, m, by = c("hex_id","year","day"), all.y = T)
hex_dead.df$Freq[is.na(hex_dead.df$Freq)] <- 0

# hex_dead.df$bin_pop_out_lockdown <- 


hex_dead.df <-
  hex_dead.df %>%
  dplyr::group_by(hex_id, year) %>%
  dplyr::arrange(day) %>%
  dplyr::mutate(dead_ma7 = 
                  rollmean(Freq, 7, align = 'center', fill = NA),
                dead_ma7_lag4 = 
                  c(rep(NA, 4), rollmean(Freq, 7, align = 'right', fill = NA)[1:(length(Freq)-4)]))

hex_dead_wide.df <- 
  hex_dead.df %>%
  dplyr::select(-Freq, -dead_ma7_lag4) %>%
  tidyr::pivot_wider(names_from = year, values_from = dead_ma7)

hex_dead_wide.df$sd_15_19 <- 
  apply(hex_dead_wide.df[,3:7], 1, FUN = sd)
hex_dead_wide.df$mean_15_19 <- 
  apply(hex_dead_wide.df[,3:7], 1, FUN = mean)
hex_dead_wide.df$dist_sd <- 
  (hex_dead_wide.df$T_20 - 
     hex_dead_wide.df$mean_15_19) /
  hex_dead_wide.df$sd_15_19 

hex_dead_wide.df$dist_sd[is.nan(hex_dead_wide.df$dist_sd)] <- 0

hex_dead_wide.df <-
  hex_dead_wide.df %>%
  dplyr::group_by(hex_id) %>%
  dplyr::arrange(day) %>%
  mutate(dist_sd_diff14 = c(dist_sd[14:length(dist_sd)], rep(NA, 13)))

save(hex_dead_wide.df, file = "hex_dead_wide.df")

model_vars.df <- 
  hex_dead_wide.df[,c('hex_id', 'day', 'dist_sd_diff14')]

model_vars.df$hex_id <- as.integer(model_vars.df$hex_id)
model_vars.df$day <- as.Date(paste0(model_vars.df$day,"-2020"), "%m%d-%Y")

hex_dead_wide.df <- 
  hex_dead.df %>%
  dplyr::select(-Freq, -dead_ma7) %>%
  tidyr::pivot_wider(names_from = year, values_from = dead_ma7_lag4)

hex_dead_wide.df$sd_15_19 <- 
  apply(hex_dead_wide.df[,3:7], 1, FUN = sd)
hex_dead_wide.df$mean_15_19 <- 
  apply(hex_dead_wide.df[,3:7], 1, FUN = mean)
hex_dead_wide.df$dist_sd <- 
  (hex_dead_wide.df$T_20 - 
     hex_dead_wide.df$mean_15_19) /
  hex_dead_wide.df$sd_15_19 

hex_dead_wide.df$dist_sd[is.nan(hex_dead_wide.df$dist_sd)] <- 0

hex_dead_wide.df <-
  hex_dead_wide.df %>%
  dplyr::group_by(hex_id) %>%
  dplyr::arrange(day) %>%
  mutate(dist_sd_lag4_diff14 = c(dist_sd[14:length(dist_sd)], rep(NA, 13)))

hex_dead_wide.df$hex_id <- 
  as.integer(hex_dead_wide.df$hex_id)
hex_dead_wide.df$day <- 
  as.Date(paste0(hex_dead_wide.df$day,"-2020"), "%m%d-%Y")

model_vars.df <- 
  merge(model_vars.df, 
        hex_dead_wide.df %>% select(hex_id, day, dist_sd_lag4_diff14), 
        by = c("hex_id", "day"))

model_vars.df <- 
  model_vars.df %>% filter(day < as.Date("2020-04-15"))

```

## Imputation

```{r}
model_vars.df$dist_sd_diff14[
  !is.finite(model_vars.df$dist_sd_diff14)] <- 0
model_vars.df$dist_sd_lag4_diff14[
  !is.finite(model_vars.df$dist_sd_lag4_diff14)] <- 0

ggplot(model_vars.df %>% filter(hex_id == 1000), aes(x=day)) + 
  geom_line(aes(y=dist_sd_diff14), colour = 'red') +
  geom_line(aes(y=dist_sd_lag4_diff14), colour = 'blue')

```


## Air quality

```{r}
names(airquality.df)[2] <- "day"
airquality_spread.df <- 
  airquality.df %>% spread(var, value)

airquality_spread.df <- 
  airquality_spread.df %>%
  select(-pmwf_conc, -ecwb_conc, -ecff_conc)

model_vars.df <- 
  merge(model_vars.df, airquality_spread.df, by = c("hex_id","day"), all.x = T)
```


```{r}
era5_climate_hex.df$day <- era5_climate_hex.df$date

era5_climate_hex_spread.df <-
  era5_climate_hex.df %>%
  dplyr::select(-date) %>%
  tidyr::pivot_wider(names_from = var, values_from = value,
                     names_prefix = "era5_") %>%
  dplyr::mutate(era5_rhum = RH(era5_temp, era5_dewp, isK = TRUE))

model_vars.df <- 
  merge(model_vars.df, 
        era5_climate_hex_spread.df,
        by = c("hex_id", "day"))
```


## Census

```{r}
# model_vars.df <- 
hex_ita_10km.df <- hex_ita_10km.sf
st_geometry(hex_ita_10km.df) <- NULL

model_vars.df <- 
  merge(model_vars.df, 
        hex_ita_10km.df, 
        by = "hex_id" ) %>%
  filter(!is.na(P1))

model_vars.df$CODREG <- as.numeric(model_vars.df$CODREG)

model_vars.df$P3[is.na(model_vars.df$P3)] <- 0

model_vars.df <-
  model_vars.df %>%
  mutate(pop_over_65 = P27 + P28 + P29,
         pop_under_65 = P1 - (P27 + P28 + P29),
         perc_over_65 = (P27 + P28 + P29) / P1,
         perc_families_over_4 = (PF5 + PF6 + PF8) / PF1,
         perc_work_outside_comune = P138 / P1,
         perc_employed = P60 / P1, 
         perc_unemployed =  P62 / P60,
         perc_degree_over_workforce = P47 / P60,
         perc_female = P3 / P1)

model_vars.df$perc_families_over_4[
  is.na(model_vars.df$perc_families_over_4)] <- 0

model_vars.df$sum_employees[
  is.na(model_vars.df$sum_employees)] <- 0
model_vars.df$sum_agedcare[
  is.na(model_vars.df$sum_agedcare)] <- 0
model_vars.df$sum_construction[
  is.na(model_vars.df$sum_construction)] <- 0
model_vars.df$sum_delivery[
  is.na(model_vars.df$sum_delivery)] <- 0
model_vars.df$sum_education[
  is.na(model_vars.df$sum_education)] <- 0
model_vars.df$sum_healthcare[
  is.na(model_vars.df$sum_healthcare)] <- 0
model_vars.df$sum_hospitality[
  is.na(model_vars.df$sum_hospitality)] <- 0
model_vars.df$sum_manufacturing.ex_meat[
  is.na(model_vars.df$sum_manufacturing.ex_meat)] <- 0
model_vars.df$sum_manufacturing.meat[
  is.na(model_vars.df$sum_manufacturing.meat)] <- 0
model_vars.df$sum_other[
  is.na(model_vars.df$sum_other)] <- 0
model_vars.df$sum_retail[
  is.na(model_vars.df$sum_retail)] <- 0
model_vars.df$sum_services[
  is.na(model_vars.df$sum_services)] <- 0
model_vars.df$sum_transport[
  is.na(model_vars.df$sum_transport)] <- 0
model_vars.df$sum_warehousing[
  is.na(model_vars.df$sum_warehousing)] <- 0
model_vars.df$sum_wholesaling[
  is.na(model_vars.df$sum_wholesaling)] <- 0
  
model_vars.df$perc_degree_over_workforce[
  !is.finite(model_vars.df$perc_degree_over_workforce)] <- 0

model_vars.df$perc_unemployed[
  !is.finite(model_vars.df$perc_unemployed)] <- 0

myLog10 <- function(x){log10(x+1)}

model_vars.df <- 
  model_vars.df %>%
  mutate_at(.vars = vars(sum_employees:sum_wholesaling),
            .funs = list(log10 = myLog10))

```


## Testing

```{r}
reg_testing.df$case_test_ratio <- 
  reg_testing.df$cases_ma7 / reg_testing.df$tests_ma7

ggplot(reg_testing.df, aes(x=date, y=case_test_ratio)) +
  geom_line() +
  facet_wrap(denominazione_regione~.)

model_vars.df <- 
  merge(model_vars.df, reg_testing.df, 
        by.x = c("CODREG", "day"), 
        by.y = c("codice_regione", "date"))
```

## Lock Down

```{r}

# hex_pop_lockdown$P1_mar8_lockdown <- hex_pop_lockdown$P1_mar9_lockdown

hex_pop_lockdown$perc_feb23 <-
  hex_pop_lockdown$P1_feb23_lockdown / hex_pop_lockdown$P1

hex_pop_lockdown$perc_mar9 <-
  hex_pop_lockdown$P1_mar9_lockdown / hex_pop_lockdown$P1

hex_pop_lockdown$perc_feb23[is.nan(hex_pop_lockdown$perc_feb23)] <- 0
hex_pop_lockdown$perc_mar9[is.nan(hex_pop_lockdown$perc_mar9)] <- 0

model_vars.df$perc_pop_lockdown <- 0
model_vars.df$perc_pop_lockdown[model_vars.df$day>as.Date("2020-03-09")] <- 1

days_lockdown1 <- 
  seq(as.Date("2020-02-23"),
      as.Date("2020-03-07"),
      by = "day")

days_lockdown2 <- 
  seq(as.Date("2020-03-08"),
      as.Date("2020-03-09"),
      by = "day")

for (this_hex_id in unique(hex_pop_lockdown$hex_id[
  hex_pop_lockdown$perc_feb23>0])) {
  this_perc <- 
    hex_pop_lockdown$perc_feb23[hex_pop_lockdown$hex_id == this_hex_id]
  for (i in 1:length(days_lockdown1)) {
    model_vars.df$perc_pop_lockdown[
      model_vars.df$hex_id == this_hex_id &
        model_vars.df$day == days_lockdown1[i]] <- 
      this_perc
  }
}

for (this_hex_id in unique(hex_pop_lockdown$hex_id[
  hex_pop_lockdown$perc_mar9>0])) {
  this_perc <- 
    hex_pop_lockdown$perc_mar9[hex_pop_lockdown$hex_id == this_hex_id]
  for (i in 1:length(days_lockdown2)) {
    model_vars.df$perc_pop_lockdown[
      model_vars.df$hex_id == this_hex_id &
        model_vars.df$day == days_lockdown2[i]] <- 
      this_perc
  }
}

model_vars.df %>% 
  group_by(day) %>% 
  summarize(ld = sum(perc_pop_lockdown>0)) %>%
  ggplot(aes(x=day,y=ld)) +
  geom_bar(stat='identity')

model_vars.df$perc_pop_out_lockdown <- 
  1 - model_vars.df$perc_pop_lockdown

model_vars.df$bin_pop_out_lockdown <- 
  ifelse(model_vars.df$perc_pop_out_lockdown < .5,
         0, 1)

model_vars.df %>% 
  group_by(day) %>% 
  summarize(ld = sum(perc_pop_out_lockdown>.5)) %>%
  ggplot(aes(x=day,y=ld)) +
  geom_bar(stat='identity')

model_vars.df %>% 
  group_by(day) %>% 
  summarize(ld = sum(bin_pop_out_lockdown)) %>%
  ggplot(aes(x=day,y=ld)) +
  geom_bar(stat='identity')

```


# Neighbours

```{r}
hex_ita_10km.nb <- 
  poly2nb(hex_ita_10km.sf %>% filter(CODREG == 3), 
          queen=TRUE)
coords <- 
  st_coordinates(st_centroid(st_geometry(hex_ita_10km.sf %>% filter(CODREG == 3))))

plot(st_geometry(hex_ita_10km.sf %>% filter(CODREG == 3)), border="grey")
plot(hex_ita_10km.nb, coords, col="red", add = TRUE)

hex_ita_10km.nb <- 
  poly2nb(hex_ita_10km.sf, queen=TRUE)

all_days <- unique(model_vars.df$day)

funNeigh1 <- function(i, hex_ita_10km.nb, all_days, model_vars.df) {
  res.df <- data.frame()
  these_neigh <- hex_ita_10km.nb[[i]]
  for (j in 1:length(all_days)) {
    this.df <- 
      model_vars.df[model_vars.df$day == all_days[j] &
                      model_vars.df$hex_id %in% these_neigh,
                    c("dist_sd_diff14", 
                      "perc_pop_out_lockdown",
                      "P1")]
    res.df <- rbind(res.df, 
                    data.frame(hex_id = i,
                               day = all_days[j],
                               neigh_weighted_mean = 
                                 weighted.mean(this.df$dist_sd_diff14,
                                               w = this.df$perc_pop_out_lockdown * this.df$P1)))
  }
  return(res.df)
}

cl <- makeCluster(10)
neigh.list <- 
  parLapply(cl, hex_ita_10km.df$hex_id, funNeigh1, 
            hex_ita_10km.nb, all_days, model_vars.df)
neigh.df <- bind_rows(neigh.list)
stopCluster(cl)

neigh.df$neigh_weighted_mean[is.nan(neigh.df$neigh_weighted_mean)] <- 0

model_vars.df <- 
  merge(model_vars.df, 
        neigh.df,
        by = c("hex_id","day"))
```

# Density

```{r}
model_vars.df$median_density_km2 <-
  pop_densities.df$median_density_km2[match(model_vars.df$hex_id,
                                            pop_densities.df$hex_id)]

model_vars.df$gini_over74 <-
  pop_densities.df$gini_over74[match(model_vars.df$hex_id,
                                     pop_densities.df$hex_id)]

model_vars.df$gini_over74[!is.finite(model_vars.df$gini_over74)] <- 0
```

# Causes of Death (Provincial level, 2017)

```{r, eval =F}
load("../cause-death-prov-2017/hex_cause_death_prov_2017.df.RData")

model_vars.df <- 
  merge(model_vars.df, 
        hex_cause_death_prov_2017.df %>%
          dplyr::select(-PROVINCIA_2017, -ITTER107),
        by = "hex_id",
        all.x = T)

model_vars.df$ITTER107 <- 
  hex_cause_death_prov_2017.df$ITTER107[match(model_vars.df$hex_id,
                                              hex_cause_death_prov_2017.df$hex_id)]
```


# Hotel rooms 

```{r}
load("../hotel-comune/hex_beds.df.RData")

model_vars.df$hotel_beds <- 
  hex_beds.df$hotel_beds[match(model_vars.df$hex_id,
                               hex_beds.df$hex_id)]

model_vars.df$hotel_beds[is.na(model_vars.df$hotel_beds)] <- 0

model_vars.df$hotel_beds_log <- log(model_vars.df$hotel_beds + 1)
```


# Smokers

```{r}
cod_reg.df <- 
  data.frame(CODREG = hex_ita_10km.sf$CODREG,
             REGIONE = hex_ita_10km.sf$REGIONE,
             stringsAsFactors = F) %>%
  dplyr::distinct(CODREG, REGIONE) %>%
  dplyr::filter(!is.na(CODREG)) %>%
  dplyr::arrange(REGIONE)

dat_smokers <- 
  read.csv("../smokers/DCCV_AVQ_PERSONE_19062020060907198.csv") %>%
  dplyr::filter(grepl("IT([A-Z])(\\d+|[A-Z])", ITTER107) &
                  !ITTER107 %in% c("ITFG","ITCD","ITD1","ITD2") & 
                  Tipo.dato == "fumatori" &
                  Misura == "per 100 persone con le stesse caratteristiche" &
                  TIME == 2019) %>%
  dplyr::arrange(Territorio)

dat_smokers$CODREG <- 
  as.numeric(cod_reg.df$CODREG)

model_vars.df$smokers <- 
  dat_smokers$Value[match(model_vars.df$CODREG, dat_smokers$CODREG)]

```

# Health status

```{r}
dat_health_status <- 
  read.csv("../health_status_reg/DCCV_AVQ_PERSONE_19062020065748989.csv") %>%
  dplyr::filter(grepl("IT([A-Z])(\\d+|[A-Z])", ITTER107) &
                  !ITTER107 %in% c("ITFG","ITCD","ITD1","ITD2") & 
                  Misura == "per 100 persone con le stesse caratteristiche" &
                  TIME == 2018) %>%
  dplyr::select(-Tipo.dato, -Misura, -TIME, -Seleziona.periodo, 
                -Flag.Codes, -Flags, -MISURA_AVQ) %>%
  tidyr::pivot_wider(names_from = TIPO_DATO_AVQ, values_from = Value)

dat_health_status$CODREG <- 
  dat_smokers$CODREG[match(dat_health_status$ITTER107, dat_smokers$ITTER107)]

colnames(dat_health_status) <- 
  gsub("0_", "", colnames(dat_health_status))

cancer_ita_reg_2019 <- 
  read_excel("../health_status_reg/2019_cancro_ita_reg.xlsx")

regioni_pop_2019 <- 
  read.csv("../health_status_reg/regioni.csv", skip = 1) %>%
  dplyr::filter(Età == "Totale") %>%
  dplyr::select(Regione, Totale.Femmine, Totale.Maschi) %>%
  dplyr::mutate(CODREG = 1:20)

cancer_ita_reg_2019 <- 
  merge(cancer_ita_reg_2019, regioni_pop_2019, by = "CODREG")

cancer_ita_reg_2019 <-
  cancer_ita_reg_2019 %>%
  dplyr::mutate(perc_breast_cancer = 
                  mammella_f / Totale.Femmine,
                perc_colorectal_cancer = 
                  (colonretto_m + colonretto_f) / 
                  (Totale.Femmine + Totale.Maschi),
                perc_lung_cancer = 
                  (polmone_m + polmone_f) / 
                  (Totale.Femmine + Totale.Maschi))

dat_health_status <- 
  merge(dat_health_status, 
        cancer_ita_reg_2019 %>% 
          dplyr::select(CODREG, 
                        perc_breast_cancer, 
                        perc_colorectal_cancer, 
                        perc_lung_cancer), by = "CODREG")

model_vars.df <- 
  merge(model_vars.df,
        dat_health_status %>% dplyr::select(-ITTER107, -Territorio), 
        by = "CODREG")
```

# Icu beds

```{r}
library(igraph)
load("../icu/hex_icu_beds.df.RData")

hex_ita_10km.sf$icu_beds <- 0
hex_ita_10km.sf$icu_beds <- 
  hex_icu_beds.df$icu_beds[match(hex_ita_10km.sf$hex_id,
                                 hex_icu_beds.df$hex_id)]
hex_ita_10km.sf$icu_beds[is.na(hex_ita_10km.sf$icu_beds)] <- 0

names(hex_ita_10km.nb) <- hex_ita_10km.sf$hex_id

g <- 
  graph_from_adj_list(
    hex_ita_10km.nb[which(unlist(lapply(hex_ita_10km.nb, function(x)length(x)>0)))], 
                      mode="all", 
    duplicate=TRUE)

neigh5 <- 
  ego(g, order = 5, nodes = V(g))

funNeighIcu <- function(i) {
  hex_ids <- neigh5[[i]]
  return(sum(hex_ita_10km.sf$icu_beds[hex_ids], na.rm = T) /
    sum(hex_ita_10km.sf$P1[hex_ids], na.rm = T))
}

hex_ita_10km.sf$perc_neigh5_icu_beds <- 
  sapply(hex_ita_10km.sf$hex_id, funNeighIcu)
hex_ita_10km.sf$perc_neigh5_icu_beds[is.na(hex_ita_10km.sf$perc_neigh5_icu_beds)] <- 0
  
model_vars.df$perc_neigh5_icu_beds <- 
  hex_ita_10km.sf$perc_neigh5_icu_beds[match(model_vars.df$hex_id,
                                             hex_ita_10km.sf$hex_id)]

```

# Income 

```{r}
load("../income/hex_income.df.RData")

hex_income.df <- 
  hex_income.df %>%
  dplyr::mutate(perc_low_income = 
                  ( X0 + X10000 ) /
                  (X0 + X10000 + X15000 + X26000 + X55000 + X75000 + X120000 + X120000.))

model_vars.df$perc_low_income <- 
  hex_income.df$perc_low_income[match(model_vars.df$hex_id, 
                                      hex_income.df$hex_id)]
```


# Modelling

```{r}
hex_wt_missing_value <- 
  unique(model_vars.df$hex_id[is.infinite(model_vars.df$dist_sd_diff14)])

hex_wt_missing_value <- 
  unique(model_vars.df$hex_id[is.infinite(model_vars.df$dist_sd_lag4_diff14)])
```


```{r}
model_vars_std.df <-
  model_vars.df %>%
  dplyr::select(hex_id, CODREG, day, perc_pop_lockdown,
                dist_sd_diff14, dist_sd_lag4_diff14, neigh_weighted_mean,
                median_density_km2, gini_over74, 
                no_conc, no2_conc, o3_conc, pm2p5_conc, pm10_conc, co_conc,  so2_conc,
                
                era5_temp, era5_rhum, era5_prec,
                
                perc_breast_cancer, perc_colorectal_cancer, perc_lung_cancer, 
                CHRONIC_DIAB, CHRONIC_HYP, CHRONIC_BRONC, CHRONIC_ALLER, CHRONIC_HEART,
                smokers,
                hotel_beds_log,
                P1, perc_female, perc_over_65, pop_over_65, perc_work_outside_comune, 
                perc_employed, perc_unemployed, perc_degree_over_workforce,
                perc_families_over_4, 
                sum_agedcare_log10, sum_construction_log10, sum_delivery_log10,
                sum_education_log10, sum_healthcare_log10, sum_hospitality_log10,
                sum_manufacturing.ex_meat_log10, sum_manufacturing.meat_log10,
                sum_other_log10, sum_retail_log10, sum_services_log10, sum_transport_log10,
                sum_warehousing_log10, sum_wholesaling_log10, 
                perc_low_income, 
                perc_neigh5_icu_beds, case_test_ratio) %>%
  dplyr::mutate_at(vars(dist_sd_diff14:case_test_ratio), scale)

model_vars_std.df$day_num <- 
  as.numeric(model_vars_std.df$day - as.Date("2020-02-24"))

pooled <- 
  lm(dist_sd_diff14 ~ 
       dist_sd_lag4_diff14 *
       neigh_weighted_mean *
       perc_pop_lockdown +
       median_density_km2 +  
       pm2p5_conc + pm10_conc + no_conc + o3_conc + 
       co_conc + no2_conc + so2_conc +
       era5_temp + era5_rhum + era5_prec + 
       perc_breast_cancer + perc_colorectal_cancer + perc_lung_cancer +
       CHRONIC_DIAB + CHRONIC_HYP + CHRONIC_BRONC + CHRONIC_ALLER + CHRONIC_HEART +
       smokers +
       hotel_beds_log + 
       perc_female + perc_over_65 + gini_over74 + 
       perc_work_outside_comune +
       perc_families_over_4 + 
       perc_employed + perc_degree_over_workforce +
       sum_agedcare_log10 + sum_construction_log10 + sum_delivery_log10 +
       sum_education_log10 + sum_healthcare_log10 + sum_hospitality_log10 +
       sum_manufacturing.ex_meat_log10 + sum_manufacturing.meat_log10 +
       sum_other_log10 + sum_retail_log10 + sum_services_log10 + sum_transport_log10 +
       sum_warehousing_log10 + sum_wholesaling_log10 +
       perc_low_income + 
       perc_neigh5_icu_beds + case_test_ratio + as.factor(day_num), 
     data=model_vars_std.df)
```


```{r fig.width=10, fig.height=13,eval=F}
vars <- names(pooled$coefficients)
vars <- vars[!grepl("(Intercept)|:", vars)]

funPlot <- function(var) {
  ggplot(model_vars_std.df) + geom_density(aes_string(var)) + theme_bw()
}

plotlist <- lapply(vars, funPlot)
do.call("grid.arrange", c(plotlist, ncol=5))
```


```{r}
predictor_labels <- 
  c(dist_sd_lag4_diff14 = "past excess mortality",
    neigh_weighted_mean = "nearby exces mortality",
    median_density_km2 = "median density",
    pm2p5_conc = "PM2.5 conc.",
    pm10_conc = "PM10 conc.",
    no_conc = "nitrogen monoxide conc.",
    o3_conc = "ozone conc.",
    co_conc = "carbon monoxide conc.",
    no2_conc = "nitrogen dioxide conc.",
    so2_conc = "sulphur dioxide",
    
    era5_temp = "temperature", 
    era5_rhum = "relative humidity", 
    era5_prec = "precipitation",
    
    perc_breast_cancer = "perc. breast cancer incidence (reg.)",
    perc_colorectal_cancer = "perc. colorectal cancer incidence (reg.)",
    perc_lung_cancer = "perc. lung cancer incidence (reg.)",
    CHRONIC_DIAB = "perc. diabetes (reg.)",
    CHRONIC_HYP  = "perc. hypertension (reg.)", 
    CHRONIC_BRONC = "perc. bronchitis (reg.)", 
    CHRONIC_ALLER = "perc. allergies (reg.)",
    CHRONIC_HEART = "perc. heart cond. (reg.)",
    smokers = "perc. smokers (reg.)",
    hotel_beds_log = "log. hotel beds",
    perc_employed = "perc. employed",
    perc_degree_over_workforce = "perc. degree (over workforce)",
    perc_female = "perc. females", 
    perc_over_65 = "perc. over 65",
    gini_over74 = "over 74 conc.",
    perc_work_outside_comune = "perc. working out of comune",
    perc_families_over_4 = "perc. families over 4",
    
    sum_agedcare_log10 = "log. agedcare employees",
    sum_healthcare_log10 = "log. healthcare employees",
    sum_manufacturing.ex_meat_log10 = "log. manufactoring employees (exc. meat)",
    sum_manufacturing.meat_log10 = "log. manufactoring employees (meat only)",
    sum_services_log10 = "log. servics employees",
    sum_warehousing_log10 = "log. warehousing employees",
    sum_transport_log10 = "log. transportation employees",
    sum_delivery_log10  = "log. delivery employees",
    sum_construction_log10 = "log. construction employees",
    sum_education_log10 = "log. education employees",
    sum_hospitality_log10 = "log. hospitality employees",
    sum_retail_log10 = "log. retail employees",
    sum_wholesaling_log10 = "log. wholesaling employees",
    sum_other_log10 = "log. other employees",
    
    perc_low_income = "perc. low income",
    case_test_ratio = "cases vs tests ratio (reg.)",
    perc_neigh5_icu_beds = "perc. ICU beds 50km radius",
    `dist_sd_lag4_diff14:perc_pop_lockdown` = "past excess mortality X lockdown",
    `neigh_weighted_mean:perc_pop_lockdown` = "near excess mortality X lockdown",
    `dist_sd_lag4_diff14:neigh_weighted_mean` = "past excess mortality X near excess mortality",
    `dist_sd_lag4_diff14:neigh_weighted_mean:perc_pop_lockdown` = "past excess mortality X near excess mortality X lockdown")
```

# Multilevel 

```{r}
library(lme4)
multivel <- 
  lmer(formula = dist_sd_diff14 ~ 1 +
       dist_sd_lag4_diff14 *
       neigh_weighted_mean *
       perc_pop_lockdown +
       median_density_km2 +  
       pm2p5_conc + pm10_conc + no_conc + o3_conc +
       co_conc + no2_conc + so2_conc +
         era5_temp + era5_rhum + era5_prec + 
       perc_breast_cancer + perc_colorectal_cancer + perc_lung_cancer +
       CHRONIC_DIAB + CHRONIC_HYP + CHRONIC_BRONC + CHRONIC_ALLER + CHRONIC_HEART +
       smokers +
       hotel_beds_log + 
       perc_female + perc_over_65 + gini_over74 + 
       perc_work_outside_comune +
       perc_families_over_4 + 
       perc_employed + perc_degree_over_workforce +
       sum_agedcare_log10 + sum_healthcare_log10 + sum_manufacturing_log10 + 
       sum_services_log10 + sum_warehousing_log10 + sum_transport_log10 + 
       sum_delivery_log10 + perc_low_income + 
       perc_neigh5_icu_beds + case_test_ratio + as.factor(day_num) + 
         (1|CODREG),
           data = model_vars_std.df)
```


```{r}

pooled_coef.df <- 
  as.data.frame(coef(summary(pooled))) %>%
  dplyr::mutate(var = rownames(coef(summary(pooled))))

multivel_coef.df <- 
  as.data.frame(coef(summary(multivel))) %>%
  dplyr::mutate(var = rownames(coef(summary(multivel))))

models_coef.df <- 
  rbind(pooled_coef.df %>% 
          dplyr::select(Estimate, `Std. Error`, var) %>%
          dplyr::mutate(model = "pooled"), 
        multivel_coef.df %>% 
          dplyr::select(Estimate, `Std. Error`, var) %>%
          dplyr::mutate(model = "multilevel"))

models_coef.df$label <- 
  predictor_labels[match(models_coef.df$var, 
                         names(predictor_labels))]

models_coef.df$label <- factor(models_coef.df$label, 
                               levels = rev(predictor_labels),
                               ordered = T)

ggsave(filename = "estimate_entiremodel.pdf", width = 11, height = 8,
       models_coef.df %>%
         dplyr::filter(!is.na(label)) %>%
         ggplot(aes(colour = model, 
                    x=Estimate,
                    y=label)) +
         geom_point() +
         geom_errorbar(aes(xmin=Estimate-`Std. Error`, 
                           xmax=Estimate+`Std. Error`)) +
         theme_bw() +
         labs(y = NULL))

ggsave(filename = "estimate_selectedvars.pdf", width = 11, height = 8,
models_coef.df %>%
  dplyr::filter(!is.na(label) &
                  !grepl("dist_sd_lag4_diff14|neigh_weighted_mean|perc_pop_lockdown", var)) %>%
  ggplot(aes(colour = model, 
             x=Estimate,
             y=label)) +
  geom_point() +
  geom_errorbar(aes(xmin=Estimate-`Std. Error`, 
                    xmax=Estimate+`Std. Error`)) +
  theme_bw() +
  labs(y = NULL, caption = "Interaction 'past excess mortality X near excess mortality X lockdown' not visualised"))

```


```{r, fig.width = 10, fig.height = 40, eval = FALSE}
all_days <- unique(hex_dead_wide.df$day[!is.na(hex_dead_wide.df$T_20)])

region.sf <- 
  read_sf("../shapefile/Italy/Limiti01012020/Reg01012020/Reg01012020_WGS84.shp")

funPlot <- function(day) {
  this_dat <- hex_dead_wide.df[hex_dead_wide.df$day == day,] 
  hex_ita_10km.sf$value <- this_dat$dist_sd[match(hex_ita_10km.sf$hex_id,
                                                  this_dat$hex_id)]
  hex_ita_10km.sf$value_cut <- cut(hex_ita_10km.sf$value, 
                                   breaks = c(-128,-50,-10,-5,0,5,10,50,128),
                                   include.lowest = T)
  return(ggplot() +
           geom_sf(data = hex_ita_10km.sf, aes(fill = value_cut), colour = NA) +
           scale_fill_brewer(palette = "YlOrRd", direction = 1,
                             drop = F) +
           geom_sf(data = region.sf, fill = NA, size = .1) +
           theme(axis.text = element_blank(),
                 axis.ticks = element_blank(),
                 legend.position = 'none') +
           labs(caption = paste0("Day: ", day),
                fill = "Diff."))
}

plot.list <- lapply(all_days, funPlot)
do.call("grid.arrange", c(plot.list, ncol=6))
```

```{r, eval = F}
hex_dead_wide.df$P1 <- 
  hex_ita_10km.df$P1[match(hex_dead_wide.df$hex_id, 
                           hex_ita_10km.df$hex_id)] 
base_geom_line <- 
  hex_dead_wide.df %>%
  filter(!is.na(P1)) %>%
  mutate(date = as.Date(as.Date(paste0("2020", day), format = "%Y%m%d"))) %>%
  group_by(date) %>%
  summarize(mean = weighted.mean(dist_sd, w = P1, na.rm = T),
            upp = quantile(dist_sd, prob = 0.975, na.rm = T),
            low = quantile(dist_sd, prob = 0.025, na.rm = T)) %>%
  ggplot(aes(x=date, y=mean)) +
  geom_line() + 
  geom_ribbon(aes(ymax = upp, ymin = low), alpha = .2) +
  theme_bw() + labs(y = NULL, x = "mean and 95% of the distribution")

```

```{r animation, eval = F}

region.sf <- 
  read_sf("../shapefile/Italy/Limiti01012020/Reg01012020/Reg01012020_WGS84.shp")
province.sf <- 
  read_sf("../shapefile/Italy/Limiti01012020/ProvCM01012020/ProvCM01012020_WGS84.shp")

hex_dead_wide.df$dist_sd[is.infinite(hex_dead_wide.df$dist_sd)] <- 0
hex_dead_wide.df$dist_sd[hex_dead_wide.df$dist_sd>200] <- 200

funPlotGif <- function(day) {
  
  require(gridExtra)
  require(cowplot)
  
  this_dat <- hex_dead_wide.df[hex_dead_wide.df$day == day,] 
  hex_ita_10km.sf$value <- this_dat$dist_sd[match(hex_ita_10km.sf$hex_id,
                                                  this_dat$hex_id)]
  hex_ita_10km.sf$value_cut <- cut(hex_ita_10km.sf$value, 
                                   breaks = rev(c(-200,-100,-50,-10,-5,-2, 2,5,10,50,150,200)),
                                   include.lowest = T)
  
  hex_ita_10km.sf$value_cut <- factor(hex_ita_10km.sf$value_cut,
                                      levels = rev(levels(hex_ita_10km.sf$value_cut)))
  
  p1 <-
    ggplot() +
    geom_sf(data = hex_ita_10km.sf, aes(fill = value_cut), colour = NA) +
    scale_fill_brewer(palette = "Spectral", direction = 1, drop = FALSE) +
    geom_sf(data = region.sf, fill = NA, size = .2) +
    geom_sf(data = province.sf, fill = NA, size = .1) +
    theme_bw() +
    theme(axis.text = element_blank(),
          axis.ticks = element_blank(),
          legend.position = c(.9,.75)) +
    labs(caption = "right-aligned 14-day m.a. | 92% comune reporting",
         fill = "Difference in SD\nfrom 2015-19 mean",
         title = sprintf("Number of deaths (every cause): 2020 / 2015-19 difference\n%s",format(as.Date(paste0("2020", day), format = "%Y%m%d"), "%d/%m/%Y"))) +
    coord_sf(ylim = c(4100000, 5200000))
  
  p2 <- 
    base_geom_line +
    geom_vline(xintercept = as.Date(paste0("2020", day), format = "%Y%m%d"), 
               alpha = .7, linetype = 2)
  
  
  return(
    plot_grid(p1, p2, align = "v", nrow = 2, rel_heights = c(8.4/10, 1.6/10))
  )
}

plot.list <- lapply(all_days, funPlotGif)

for (i in 1:length(plot.list)) {
  print(i)
  file_name = sprintf("../model/tiff/%03d.tiff", i)
  ggsave(filename = file_name, plot.list[[i]], width = 6.5, height = 8)
}
# convert -delay 50 -quality 100 *.tiff output.mpeg
# ffmpeg -i output.mpeg -c:v libx264 -strict -2 output.mp4
```

